# Generated by Django 3.2.7 on 2021-09-18 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('medical_type', models.CharField(max_length=100)),
                ('buy_price', models.CharField(max_length=10)),
                ('sell_price', models.CharField(max_length=10)),
                ('CGST', models.CharField(max_length=10)),
                ('SGST', models.CharField(max_length=10)),
                ('batch_no', models.CharField(max_length=100)),
                ('shelf_no', models.CharField(max_length=100)),
                ('exp_date', models.DateField()),
                ('mfg', models.DateField()),
                ('description', models.TextField()),
                ('in_stock', models.IntegerField()),
                ('quantity_in_strip', models.IntegerField()),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salt_name', models.CharField(max_length=100)),
                ('salt_quantity', models.CharField(max_length=100)),
                ('salt_quantity_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('medicine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.medicine')),
            ],
        ),
    ]
